### ISSUE TITLE
Allow external services (EPNS) to hook into notification system

### ISSUE THREAD

**Issue by RickVM** [lens-protocol/core#116]
I would like to create a push notification server with EPNS. Currently, the Lens protocol notification API will only return notifications for the logged-in user. 

In what ways could we allow authorized services to access notifications? 
And once we've fixed that, perhaps rather than having to pull the API for changes, it would be ideal if we can use webhooks or WebSockets to listen for new notifications.

**Comment by donosonaumczuk** [comment]
Hey Rick, sorry for the delay on the response. 

Feel free to build notification services for Lens, that would be awesome. 

For API specific questions, I'll kindly ask you to redirect them to the `#lens-api` channel in our [official Discord](https://discord.gg/lensprotocol). Thank you!
