### ISSUE TITLE
Additional status for collect module

### ISSUE THREAD

**Issue by michaelvogt** [lens-protocol/core#132]
It is great to see the already available collect modules. With them, we can easily cover the general use cases of our app ([b.trax](https://showcase.ethglobal.com/lfgrow/b-trax-mi7o7)).

Unfortunately, not to 100%. We'd need additional status for a collect.

In our app, sound files are attached to the publications, which musicians can buy (price from $0 - ...), for which we believe collecting is the correct Lens 'action' to use.

So far, so good. 

But from here we have additional status to handle, like if the sound file was downloaded or used in a song by the musician, [edit] when (date) the publication was collected, and several more.
Now the question is, where to store this additional data. I don't see a way to do so in the collect module itself.

I'm happy to create a collect module that fits exactly to our use case, but I think this could be a feature that's potentially valuable outside our app. 

So my question is, if you see a way to extend the collect module to hold additional status, or if it's better when I create a new module myself.

**Comment by michaelvogt** [comment]
Here is a first implementation of the issue described above. In it's current state the implementation is pretty app specific, and the state specific to a collector might even be better placed into the collect NFT, but maybe the source shows what I am asking for.

https://github.com/nftCol1ective/lens-protocol/tree/btrax_collect

**Comment by donosonaumczuk** [comment]
Hey @michaelvogt! Sorry for the huge delay. 

I have a few questions.


> (...) But from here we have additional status to handle, like if the sound file was downloaded or used in a song by the musician (...)

1. Should this be on-chain? In case this should be on-chain, why not being in an external contract instead of being in the module itself? So you can map your publication to that custom state, and having a module that is generic.

>  (...) [edit] when (date) the publication was collected, and several more. (...)

2. The collected date could be obtained from the collect transaction itself, it has the timestamp. But if you need/want to have it on-chain, then probably storing it in the module makes sense, as I can't see any other trustless way of doing it (unless you use a wrapper contract that does the collect and stores the date, but maybe adds to much unnecessary complexity in that case).

---
Looking forward to your answers.

**Comment by michaelvogt** [comment]
Hello Alan.

Thanks for your comment.

Well, with this issue I try to understand if there is a possibility that such state could be available in Lens or not. If so, handling such state could be much easier than handling it separately. As Modules are the extension points of Lens, this is what I startet with.

If not, there are other ways available to achieve what I need to do. 

> 1. Should this be on-chain? In case this should be on-chain, why not being in an external contract instead of being in the module itself? So you can map your publication to that custom state, and having a module that is generic.
> 
Yes that would be an (inconvenient) alternative. 
Also need to check if it is possible to store custom metadata in the collect nft.

> 2. The collected date could be obtained from the collect transaction itself, it has the timestamp. But if you need/want to have it on-chain, then probably storing it in the module makes sense, as I can't see any other trustless way of doing it (unless you use a wrapper contract that does the collect and stores the date, but maybe adds to much unnecessary complexity in that case).
> 
As far as I understand, the transaction timestamp could be used, but it seems inconvenient to get the transaction every time the date is needed for a layout on the front end. But maybe I'm missing something here.

**Comment by vicnaum** [comment]
Closing this, as it seems to be related to V1.

If this is still relevant to V2 - please reopen or create a new issue.
