### ISSUE TITLE
Setting up locally vs using Docker

### ISSUE THREAD

**Issue by dabit3** [lens-protocol/core#133]
What are the main benefits of using Docker vs just running locally?

I wonder if it would be good to outline that developers could also run locally, and what the tradeoffs are for doing so.

I think that some developers might have an easier time running locally, and if there was some explanation around how to do it and what the tradeoffs are vs running in docker, it would be helpful (me included).

Also might be cool to consider using something like GitPod which would allow someone to deploy, run, and change files easily using the in-browser VS Code editor.

**Comment by michaelvogt** [comment]
Yes, ignoring the docker setup and just use the sources from the repo directly was already discussed on Lens' discord. Works like a charm as soon as you have found a way to do the initial generation of the ts types on Windows. Then change the scripts in the package file to not call hardhat clear, to prevent deletion of the ts types.

I'd like to add, that some explanation how to setup lens when using it from npm would be very much appreciated. That might be the cleanest way to use Lens once to get the setup done.

**Comment by Zer0dot** [comment]
I think that makes sense. @donosonaumczuk wdyt?

**Comment by donosonaumczuk** [comment]
Yeah I agree, we should add non-docker instructions. I will do it as soon as I have a free time.

**Comment by dabit3** [comment]
Thanks everyone in this thread and thank you @donosonaumczuk this would be amazing to see!

**Comment by LintonAchmad** [comment]
Thanks @dabit3 for this discussion. I was actually stuck setting up with Docker. I was getting `error eacces permission denied mkdir '/.npm' ` on `npm install --save-dev hardhat`. I'm new when it comes to Docker and wasn't sure if the issue was linked to the Docker image or not. Anyway this issue got me through it - https://github.com/lens-protocol/core/issues/104 - thanks fam.

**Comment by donosonaumczuk** [comment]
Docker is not used anymore
