### ISSUE TITLE
Communities as a native feature

### ISSUE THREAD

**Issue by vorcigernix** [lens-protocol/core#139]
I would like to see a community as a different type of post (publicationTypes: COMMUNITY) that would allow me to work easily with the communities in a similar way the lenster does this. On top of publication POST functionality, it will be nice to be able to fetch communities I subscribed to and fulltext search.

**Comment by donosonaumczuk** [comment]
Hey Adam, we have plans to bring native community feature to Lens. If you, or anyone reading, have any ideas for community features feel free to drop them here!
