### ISSUE TITLE
Open Letter Signature

### ISSUE THREAD

**Issue by hanymorcos** [lens-protocol/core#142]
Only addresses affiliated with an open letter signature are eligible at this time.

I'm getting this error when I try to claim my handle?

I'm newbie.

Hany

**Comment by donosonaumczuk** [comment]
I deleted the message above as it contained a scam link.

The open letter as whitelisting condition was only available for those who signed before May 5th 2022. We are continuously adding whitelisting conditions, but we are also working on bringing permissionlesss minting to Lens profiles!
