### ISSUE TITLE
Adding Source Endpoint which returns a list of appIds

### ISSUE THREAD

**Issue by Ankit85** [lens-protocol/core#148]
So right now there is no endpoint which returns list of appIds. As the lens is growing more and more apps built.  So its really hard to keep track all those apps  and the content which are published on it. 

A source endpoint which returns a list of appIds and with the total publication count for that appId.

**Comment by donosonaumczuk** [comment]
Bringing @joshstevens19 into the conversation

**Comment by donosonaumczuk** [comment]
Hey! Sorry, for API-specific questions I suggest you to ask in `#lens-api` channel in our [official Discord](https://discord.gg/lensprotocol), thank you!
