### ISSUE TITLE
Invalid Contract Adress or ENS name when running create-profile hardhat task

### ISSUE THREAD

**Issue by laurentknauss** [lens-protocol/core#149]
When i run "npx hardhat create-profile --network localhost", i get the following error msg in the command line: 

reason :  'Invalid contract address or ENS name'
code : ' INVALID ARGUMENT'
argument: 'INVALID_ARGUMENT'
value: undefined

I follow along with the quick set up guide & i am stuck in the create-profile.ts  phase.
Thx for any insights.

Setup : Ubuntu 22 & docker v20.10.17

**Comment by donosonaumczuk** [comment]
Hey! Can you provide more context? Are you executing the create-profile script as it is in the docs?

Also, feel free to pop in our [official Discord](https://discord.gg/lensprotocol) for a more dynamic Q&A.

**Comment by abondance68** [comment]
Hi, i did indeed posted this issue with details on the official  discord on august 10th in the #protocol-questions.

**Comment by abondance68** [comment]
?????

**Comment by donosonaumczuk** [comment]
Closing this as we now use Foundry scripts instead of Hardhat ones. Sorry for the big delay.
