### ISSUE TITLE
Quick setup instructions missing directory creation

### ISSUE THREAD

**Issue by melzubeir** [lens-protocol/core#156]
In the [Quick Setup](https://docs.lens.xyz/docs/quick-setup) documentation it should probably say:

$ git clone git@github.com:lens-protocol/core.git **lens-protocol**

because the next step assumes that this is the directory where the clone was created.

**Comment by aarav1656** [comment]
yep! I have also faced this, because in next step they suggest cd lens-protocol.
and git clone into core folder.

it may be cd core in next step

**Comment by alcalawil** [comment]
`cd core` instead

**Comment by LintonAchmad** [comment]
Agreed with updating the dev docs.

**Comment by donosonaumczuk** [comment]
Docs updated https://github.com/lens-protocol/core?tab=readme-ov-file#1-clone-the-repository
