### ISSUE TITLE
Unable to deploy the protocol - Cannot find '../typechain-types' issue

### ISSUE THREAD

**Issue by BriceGD7** [lens-protocol/core#160]
Hi ! I dev on windows, I already had issues with the Quick Setup guide when configuring the docker container.
I choosed not to use it and I got other issues for deploying the protocol in a local blockchain.

Here is what I got in the first terminal:
![image](https://user-images.githubusercontent.com/116149179/197459399-9a09f86a-183c-400b-8954-0403bef32954.png)
(This is in french but means SKIP_LOAD is not recognized as an internal or external control.)
![image](https://user-images.githubusercontent.com/116149179/197459670-9c2568e6-14c5-4d68-a83b-6e974ff74fa1.png)
I fixed that with "npm ci" in the first terminal and I got:
![image](https://user-images.githubusercontent.com/116149179/197459968-20f07474-5ad3-4235-99fd-d2d14b3b4257.png)
So I guess this is working fine and I just have to keep this window open and dev in another terminal.

I have the exact same issues in the second shell but couldn't fix it:
![image](https://user-images.githubusercontent.com/116149179/197460904-b5b15529-0bf9-4f3b-98fb-e66121826779.png)
This "Cannot find module '../typechain-types'" issue is the same than previously. I try this:
![image](https://user-images.githubusercontent.com/116149179/197460248-4ddf2552-f615-4a2d-8398-90a1be798203.png)
![image](https://user-images.githubusercontent.com/116149179/197460287-c12380dc-f8d2-4565-9d08-3d024febb7a4.png)
And now I got issues with Hardhat (not recognized as internal or external control)..

I tried to set SKIP_LOAD value, to update full-deploy.ts file but nothing is working...
Thank you for your help, and tell me if you have further questions !

**Comment by Pryority** [comment]
I had the same issue, but then was able to generate the typechain-types by running `npm run compile`

**Comment by donosonaumczuk** [comment]
Yes, compiling should do the trick. However, now we switched to foundry and we have foundry scripts. I will close this issue, sorry for the delay.
