### ISSUE TITLE
feat(request): Add ability to invite 

### ISSUE THREAD

**Issue by m0ham3dx** [lens-protocol/core#168]
# Motivation 

- Ability to invite people from my [`Lenster Profile`](https://lenster.xyz/u/m0ham3dx) 

Current Discussions indicate there is an unwillingness to add this feature 
![image](https://user-images.githubusercontent.com/82266083/221416384-83e1f58f-e799-4569-afaa-e753ea7c9585.png)

- If the objective of a social media network is to onboard more people , a closed invite only system is ineffective 

# Solution 

Add ability to invite in Lenster

**Comment by donosonaumczuk** [comment]
hey.xyz (previously lenster.xyz) is a client powered by Lens. If you have any suggestion for the Lens Protocol, you can make a proper formal LIP [here](https://github.com/lens-protocol/LIPs).
