### ISSUE TITLE
Unable to accept invite our discord

### ISSUE THREAD

**Issue by DannyIMia** [lens-protocol/core#177]
I want to join our community so cannot connect to discord. Can u send me the availble link or add me to our discord?

**Comment by Coder-aadarsh** [comment]
https://discord.com/invite/lensprotocol

**Comment by granitestatue** [comment]
hi all
I am instantly getting "unable to accept invite" when connecting to the link
is there any workaround to this?

**Comment by donosonaumczuk** [comment]
The link provided above is correct. Not sure why you could be getting this error message.

Sorry, I am closing this as it is not related to Lens smart contracts.
