### ISSUE TITLE
Can't claim handle on waitlist wallet

### ISSUE THREAD

**Issue by Frans86** [lens-protocol/core#183]
i'm already whitelist from phaver but when i tried claim lens profile it keep show "Something went wrong when claiming"
keep getting this message after claim whitelist on phaver,note already clear chache,flus dns,etc but still get same message,change browser using mobile app stil got same error.
on
@orbapp_
it said already locked
![aqer](https://github.com/lens-protocol/core/assets/34282181/9885dd74-359d-402c-9b8a-50fa6f824f5b)
![aqrt](https://github.com/lens-protocol/core/assets/34282181/b09e0b07-0feb-4824-a391-32f0cb12eed0)
![aqty](https://github.com/lens-protocol/core/assets/34282181/b7c2bc00-e0ed-4df1-88ea-77b52c9f73f0)
![f2a8ac23-f8ef-43ff-a997-3ee3a1562244](https://github.com/lens-protocol/core/assets/34282181/b3cfa25f-56db-4a10-858f-c1ef681e3914)

**Comment by II8888** [comment]
Try refreshing

**Comment by donosonaumczuk** [comment]
No more waitlist
