### ISSUE TITLE
[Question] What when Polygon move to ZK (Validium)?

### ISSUE THREAD

**Issue by danimesq** [lens-protocol/core#185]
Polygon PoS is moving, in Polygon 2.0, to be a ZK Validium.

How can Lens' social data still be public, when ZK is about secrets?

**Comment by Vtalike** [comment]
> Polygon PoS is moving, in Polygon 2.0, to be a ZK Validium.
> 
> 
> 
> How can Lens' social data still be public, when ZK is about secrets?

**Comment by Wyzeman10** [comment]
it will happen soon

**Comment by tranminhtamqtd** [comment]
ok men

**Comment by donosonaumczuk** [comment]
Lens is moving to the Lens Network (powered by zkSync stack). [Read more here](https://app.t2.world/article/clw6l2z0018727620mc1dq26xr2).
