### ISSUE TITLE
Unlocking the Power of Tokens: How They Drive Engagement and Governance in Web3 Social Networks

### ISSUE THREAD

**Issue by neketskk** [lens-protocol/core#190]
In a social network powered by web3 technology, a token is essential for various reasons. Firstly, the token serves as a means of incentivizing users to actively participate in the network by rewarding them for their contributions. Additionally, the token can be used for governance purposes, allowing users to have a say in the decision-making processes of the platform. Moreover, the token can facilitate seamless and secure transactions within the network, enabling users to exchange value and access various services. Overall, the token plays a crucial role in enhancing the functionality, sustainability, and overall user experience of a web3 social network.(wen dao)

**Comment by donosonaumczuk** [comment]
This is not the place for this topic. You can make a proper formal LIP [here](https://github.com/lens-protocol/LIPs).
