### ISSUE TITLE
Request for Removal of Spam Flag

### ISSUE THREAD

**Issue by 0xjoa** [lens-protocol/core#191]
Hello,

I am using a Lens Handle, a product of the Lens protocol. However, my content has been marked as spam due to its perceived low quality. I need assistance in resolving this issue. Could you provide guidance on how to have the spam flag removed from my content?

Thank you,
Lens Handle: Cngzx0

**Comment by donosonaumczuk** [comment]
Hello @0xjoa, this issues are supposed to be related to Lens Protocol core smart contracts.

Please, redirect this to the [Lens official Discord server](https://discord.com/invite/lensprotocol).
