### ISSUE TITLE
Degrees of Separation bug

### ISSUE THREAD

**Issue by iPaulPro** [lens-protocol/core#193]
I created a post with the Degrees of Separation module set to 2 degrees, but no profile is able to reference this post, including me.

The post: https://share.lens.xyz/p/0xd8-0x0162

The transaction: https://polygonscan.com/tx/0x2c173d4fff2b5475a35673c01450d9fb50ef54ee8ff79f40a6adcafd6d430aca

I suspect this might have something to do with my wallet having multiple Lens Profiles. I've tried submitting a `comment` transaction directly, without using the API, but gas cannot be estimated as the tx will fail (so this isn't an API issue).

**Comment by donosonaumczuk** [comment]
Good post, I tried replying and it failed, as you said. We were debugging and it worked when we went through the contracts directly, so it seems it might be a Lens API bug. The backend team will work on it.

**Comment by iPaulPro** [comment]
Thanks! 

If it were an API issue shouldn't I be able to post a comment directly to the LensHub contract? That's not working, unless I did something wrong (I don't think I did, as I can successfully comment on any other post with the exact same calldata).

Are you able to comment on my post linked, directly from the contract?

**Comment by donosonaumczuk** [comment]
Yes, here you have [a tx of a comment to your post](https://polygonscan.com/tx/0x44f113080f24f68df1f3f82bbb22ee3f213874bd6b58037e18668610af64fe8d). We just put "test" as contentURI, which is not a URI that follows the Lens metadata standards, so it will not be indexed in the Lens API (so, you won't see it in the feed).

**Comment by Jsydog222** [comment]
> Thanks!
> 
> If it were an API issue shouldn't I be able to post a comment directly to the LensH
ub contract? That's not working, unless I did something wrong (I don't think I did, as I can successfully comment on any other post with the exact same calldata).
> 
> Are you able to comment on my post linked, directly from the contract?

[](url)

**Comment by iPaulPro** [comment]
I've been informed that this is now resolved.
